import type { Metadata } from "next";
import "./globals.css";
import "./override.css";



export const metadata: Metadata = {
  title: "Binarytree | Your Tech Portfolio Simplified",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Providers> */}
          {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
