import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./override.css";

import {Header} from "./main/Header";
import {Footer} from "./main/Footer";


export const metadata: Metadata = {
  title: "Binarytree | Your Tech Portfolio Simplified",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Providers> */}
          {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
